version: 2.1
jobs:
  tests:
    docker:
      - image: circleci/node:latest-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-npm-deps--{{ checksum "package.json" }}

      - run: npm install
      - run: npm run test

      - save_cache:
          key: v1-npm-deps--{{ checksum "package.json" }}
          paths:
            - node_modules
            - .cache

workflows:
  version: 2
  test:
    jobs:
      - tests:
          filters:
            branches:
              ignore:
                - v1